FROM jenkins/jenkins
# FROM jenkinsci/blueocean 

MAINTAINER hariomsaini0011@gmail.com

# Uncomment the following to specify no. of executors
# COPY executors.groovy /usr/share/jenkins/ref/init.groovy.d/executors.groovy
USER root